highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl:
title: Francesco Gapito's Resume
name: Francesco Gapito
email: francesco.gapito@gmail.com
email_full: mailto:francesco.gapito@gmail.com
website: francescogapito.it
website_full: https://www.francescogapito.it
github: fgapito
twitter: fgapito
tel: 
tel_full: 
google_maps: 'https://goo.gl/maps/8EkDvchZZKUo1qdn6'
address:
  street: 
  postcode: 
  city: Bologna
  country: Italy
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
